---
title: "Lab1: Revision"
output: html_notebook
---

## 1 Basic commands

```{r}
# Assignment
x <- c(1,3,2,5)
y = c(3,1,2)
x
y
```

```{r}
# Helper
?matrix
```

```{r}
# Atomic vector
c(length(x), length(y))
```

```{r}
# Broadcasting
z <- c(4,3,3)
y + z
```

```{r}
ls()
```

```{r}
rm(list=ls())
```

```{r}
# Matrix creation
x = matrix(c(1,2,3,4),2,2)
x
```

```{r}
matrix(c(1,2,3,4), 2,2, byrow=TRUE)
```

```{r}
sqrt(x)
x^2
```

```{r}
# Correlation of variables
y = rnorm(50)
z = y + rnorm(50, mean=50, sd=.1)
cor(y, z)
```

```{r}
# Random generation
set.seed(9556)
a = rnorm(50)
a
```

```{r}
# Statistics
mean(a)
var(a)
sqrt(var(a))
sd(a)
```

```{r}
# Normal distribution
x=rnorm(100)
y=rnorm(100)
plot(x,y)
plot(x,y,xlab="player 1", ylab="player 2", main="X vs Y")
```

```{r}
# Export figures
pdf("Fig-1.pdf")  # jpeg, png, bmp
plot(x,y,col="green")
dev.off()
```

```{r}
# Sequences
a = seq(1,10)
a
b = 1:10
b
c = seq(-pi, pi, length=50)
c

```

```{r}
# Contour line
x = 1:10
y = x
f = outer(x,y,function(x,y)cos(y)/(1+x^2))
contour(x,y,f)
contour(x,y,f,nlevels=45, add=T)
fa = (f-t(f))/2
contour(x,y,fa,nlevels=45)
```

```{r}
# Exclude by index
A <- matrix(1:16,4,4)
A[-c(1,3),]
dim(A)
```

```{r}
# Import data
Auto <- read.table("Auto.data",header=T,na.strings="?")
dim(Auto)
```
```{r}
# Head
Auto[1:5,]
```
```{r}
# Inspect names of columns
names(Auto)
```

```{r}
# Scatter plot
plot(Auto$cylinders, Auto$mpg)
```

```{r}
# Boxplot for categorical data
cylinders <- as.factor(Auto$cylinders)
plot(cylinders, Auto$mpg)
```

```{r}
# Histogram
hist(Auto$mpg, col=2, breaks=15)
```

```{r}
# Scatter plot matrix
pairs(Auto[,-9])
pairs(~ mpg + displacement + horsepower + weight + acceleration, Auto)
```

```{r}
plot(horsepower, mpg)
identify(horsepower, mpg, name)
```
```{r}
summary(Auto)
```
```{r}
summary(mpg)
```

